package prjpayroll;

public class JPayroll extends javax.swing.JFrame {

    public JPayroll() {
        initComponents();

        groupButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnpaymentoptions = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfEmployeeName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfHoursWorked = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfRatePerHour = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfTotalDeductions = new javax.swing.JTextField();
        btnProcessSalary = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rbCashier = new javax.swing.JRadioButton();
        rbBank = new javax.swing.JRadioButton();
        cbBank = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Details"));

        jLabel1.setText("Employee Name:");

        jLabel2.setText("Hours Worked:");

        jLabel3.setText("Rate per Hour:");

        jLabel4.setText("Total Deductions:");

        btnProcessSalary.setText("Process Salary");
        btnProcessSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessSalaryActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Payment Options"));

        rbCashier.setText("NUB Cashier");

        rbBank.setText("Bank");

        cbBank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BDO", "BPI", "CHINABANK", "METROBANK", "RCBC" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbBank, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addComponent(cbBank, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbCashier)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(rbCashier)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbBank))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfHoursWorked)
                    .addComponent(tfRatePerHour)
                    .addComponent(tfTotalDeductions)
                    .addComponent(tfEmployeeName)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnProcessSalary)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfHoursWorked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfRatePerHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTotalDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnProcessSalary)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String empName;
    private String paymentOption;
    private double grossPay;
    private double netPay;
    private double taxAmount;
    private double totalDeductions;
    private double hoursWorked;
    private double ratePerHour;

    public void setEmpName(String empName) {
        this.empName = empName;
    }

    public String getEmpName() {
        return this.empName;
    }

    public void setHoursWorked(double hoursWorked) {
        this.hoursWorked = hoursWorked;
    }

    public double getHoursWorked() {
        return this.hoursWorked;
    }

    public void setRatePerHour(double ratePerHour) {
        this.ratePerHour = ratePerHour;
    }

    public double getRatePerHour() {
        return this.ratePerHour;
    }

    public void setTotalDeductions(double totalDeductions) {
        this.totalDeductions = totalDeductions;
    }

    public double getTotalDeductions() {
        return this.totalDeductions;

    }

    public void setNetPay(double totalDeductions) {
        double ita, gp, np;
        gp = getGrossPay();
        ita = getIncomeTaxAmount();
        np = gp - totalDeductions - ita;
        this.netPay = np;
    }

    public double getNetPay() {
        return this.netPay;
    }

    public void setGrossPay(double hoursWorked, double ratePerHour) {
        double grossPay;
        grossPay = ratePerHour * hoursWorked;
        this.grossPay = grossPay;
    }

    public double getGrossPay() {
        return this.grossPay;
    }

    public void setIncomeTaxAmount(double gross) {
        double incometax = 0;
        if (gross >= 10000 && gross < 15000) {
            incometax = 0.10 * gross;
        } else if (gross >= 15000 && gross < 20000) {
            incometax = 0.15 * gross;
        } else if (gross >= 20000 && gross < 25000) {
            incometax = 0.2 * gross;
        } else if (gross >= 25000 && gross < 30000) {
            incometax = 0.25 * gross;
        } else if (gross >= 30000) {
            incometax = 0.30 * gross;
        }

        this.taxAmount = incometax;
    }

    public double getIncomeTaxAmount() {
        return this.taxAmount;
    }

    public void groupButtons() {
        rbtnpaymentoptions.add(rbCashier);
        rbtnpaymentoptions.add(rbBank);
    }

    public String getPaymentOptionInfo() {
        String paymentOption;

        if (rbCashier.isSelected()) {
            paymentOption = "Cashier";
        } else {
            paymentOption = "Bank - " + String.valueOf(cbBank.getSelectedItem());
        }
        return this.paymentOption = paymentOption;
    }

    private void btnProcessSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessSalaryActionPerformed
        String empName = tfEmployeeName.getText();
        setEmpName(empName);
        
        double hoursWorked = Double.parseDouble(tfHoursWorked.getText());
        setHoursWorked(hoursWorked);
        
        double ratePerHour = Double.parseDouble(tfRatePerHour.getText());
        setRatePerHour(ratePerHour);
        
        double totalDeductions = Double.parseDouble(tfTotalDeductions.getText());
        setTotalDeductions(totalDeductions);
        
        setGrossPay(hoursWorked, ratePerHour);
        setIncomeTaxAmount(getGrossPay());
        setNetPay(totalDeductions);
        
        String empNameOp = getEmpName();
        String hoursWorkedOp = String.valueOf(getHoursWorked());
        String ratePerHourOp = String.valueOf(getRatePerHour());
        String deductionsOp = String.valueOf(getTotalDeductions());
        String grossPayOp = String.valueOf(getGrossPay());
        String taxOp = String.valueOf(getIncomeTaxAmount());
        String netPayOp = String.valueOf(getNetPay());
        String paymentOptionOp = getPaymentOptionInfo();
        JPayrollDetails jpd = new JPayrollDetails();
        jpd.printInfo(empNameOp, hoursWorkedOp, ratePerHourOp, deductionsOp,
                grossPayOp, taxOp, netPayOp, paymentOptionOp);
        jpd.setVisible(true);


    }//GEN-LAST:event_btnProcessSalaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JPayroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcessSalary;
    private javax.swing.JComboBox<String> cbBank;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rbBank;
    private javax.swing.JRadioButton rbCashier;
    private javax.swing.ButtonGroup rbtnpaymentoptions;
    private javax.swing.JTextField tfEmployeeName;
    private javax.swing.JTextField tfHoursWorked;
    private javax.swing.JTextField tfRatePerHour;
    private javax.swing.JTextField tfTotalDeductions;
    // End of variables declaration//GEN-END:variables

}
